Fix errors generated by pipeline docker build on 'develop' branch.
Printout of fixed errors:
 - Startup.cs(50,13): error SA1515: Single-line comment should be preceded by blank line [/src/CDTS Blazor/CDNApplication.csproj]
 - Startup.cs(123,21): error SA1515: Single-line comment should be preceded by blank line [/src/CDTS Blazor/CDNApplication.csproj]
 - Startup.cs(114,13): error CA1062: In externally visible method 'void Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IAntiforgery antiforgery)', validate parameter 'app' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument. [/src/CDTS Blazor/CDNApplication.csproj]